import { BaseCard, CIS } from "../types";

const cards_cis_base: Omit<BaseCard, "faction">[] = [
  {
    name: "AAT Battle Tank",
    filename: "aat",
    keywords: [
      "ai_action",
      "armor_x",
      "arsenal_x",
      "barrage",
      "hover_x",
      "weak_point_x",
      "fixed",
      "critical_x",
      "high_velocity",
      "impact_x",
    ],
    hiddenFromPrint: false,
  },
  {
    name: "B1 Battle Droids",
    filename: "b1",
    keywords: ["ai_action", "coordinate"],
    hiddenFromPrint: false,
  },
  {
    name: "B2 Super Battle Droids",
    filename: "b2",
    keywords: ["ai_action", "impact_x"],
    hiddenFromPrint: false,
  },
  {
    name: "BX-Series Droid Commandos",
    filename: "bx",
    keywords: [
      "jump_x",
      "ai_action",
      "impervious",
      "scale",
      "scout_x",
      "sharpshooter_x",
    ],
    hiddenFromPrint: false,
  },
  {
    name: "BX-Series Droid Commandos (Strike Team)",
    filename: "bx_strike",
    keywords: [
      "jump_x",
      "ai_action",
      "detachment",
      "heavy_weapon_team",
      "scale",
      "scout_x",
      "sharpshooter_x",
    ],
    hiddenFromPrint: false,
  },
  {
    name: "Count Dooku (Darth Tyranus)",
    filename: "dooku",
    keywords: [
      "cunning",
      "deflect",
      "direct",
      "immune_pierce",
      "makashi_mastery",
      "master_of_the_force",
      "impact_x",
      "pierce_x",
      "pierce_x",
      "scatter",
      "suppressive",
    ],
    hiddenFromPrint: false,
  },
  {
    name: "General Grievous (Sinister Cyborg)",
    filename: "grievous",
    keywords: [
      "block",
      "entourage",
      "immune_pierce",
      "jedi_hunter",
      "relentless",
      "scale",
      "critical_x",
      "impact_x",
      "pierce_x",
      "versatile",
    ],
    hiddenFromPrint: false,
  },
  {
    name: "Super Tactical Droid (Kalani)",
    filename: "kalani",
    keywords: [
      "strategize_x",
      "direct",
      "exemplar",
      "reinforcements",
      "sharpshooter_x",
      "lethal_x",
    ],
    hiddenFromPrint: false,
  },
  {
    name: "Super Tactical Droid (Kraken)",
    filename: "kraken",
    keywords: [
      "strategize_x",
      "charge",
      "exemplar",
      "override",
      "sharpshooter_x",
      "lethal_x",
    ],
    hiddenFromPrint: false,
  },
  {
    name: "IG-100 MagnaGuard (Prototype Assassin Droids)",
    filename: "magnaguard_prototype",
    keywords: [
      "ai_action",
      "charge",
      "immune_melee_pierce",
      "special_issue",
      "unhindered",
    ],
    hiddenFromPrint: false,
  },
  {
    name: "Persuader-Class Tank Droid",
    filename: "persuader",
    keywords: [
      "armor_x",
      "arsenal_x",
      "programmed",
      "reposition",
      "transport",
      "weak_point_x",
      "critical_x",
      "fixed",
      "impact_x",
      "ion_x",
    ],
    hiddenFromPrint: false,
  },
  {
    name: "Persuader-Class Tank Droid (Prototype Tank Droid)",
    filename: "persuader_prototype",
    keywords: [
      "armor_x",
      "arsenal_x",
      "direct",
      "programmed",
      "reposition",
      "special_issue",
      "weak_point_x",
      "fixed",
      "impact_x",
      "ion_x",
      "critical_x",
    ],
    hiddenFromPrint: false,
  },
  {
    name: "Poggle the Lesser (Public Leader of the Geonosians)",
    filename: "poggle",
    keywords: ["jump_x", "compel", "entourage", "override", "weighed_down"],
    hiddenFromPrint: false,
  },
  {
    name: "Super Tactical Droid (Commanding Controller)",
    filename: "super_tactical",
    keywords: [
      "strategize_x",
      "direct",
      "exemplar",
      "override",
      "sharpshooter_x",
      "lethal_x",
    ],
    hiddenFromPrint: false,
  },
  {
    name: "T-Series Tactical Droid (Progammed for Strategy)",
    filename: "tactical_droid",
    keywords: ["bolster_x", "direct", "exemplar"],
    hiddenFromPrint: false,
  },

  {
    name: "Asajj Ventress (Seperatist Assassin)",
    filename: "",
    keywords: [
      "jump_x",
      "deflect",
      "independent_x",
      "indomitable",
      "immune_pierce",
      "jarkai_mastery",
      "relentless",
      "impact_x",
      "pierce_x",
    ],
    hiddenFromPrint: true,
  },
  {
    name: "Maul (Impatient Apprentice)",
    filename: "",
    keywords: [
      "jump_x",
      "cover_x",
      "death_from_above",
      "direct",
      "retinue",
      "scale",
      "weighed_down",
      "pierce_x",
      "suppressive",
    ],
    hiddenFromPrint: true,
  },
  {
    name: "Sun Fac (Ruthless Lieutenant)",
    filename: "",
    keywords: [
      "equip",
      "impervious",
      "scale",
      "steady",
      "sharpshooter_x",
      "we_are_not_regs",
      "fire_support",
    ],
    hiddenFromPrint: true,
  },
  {
    name: "Geonosian Warriors (Soldiers of the Hive)",
    filename: "",
    keywords: ["jump_x", "scale", "death_from_above", "weighed_down"],
    hiddenFromPrint: true,
  },
  {
    name: "IG-100 MagnaGuard",
    filename: "",
    keywords: [
      "ai_action",
      "charge",
      "guardian_x",
      "immune_melee_pierce",
      "retinue",
      "unhindered",
    ],
    hiddenFromPrint: true,
  },
  {
    name: "DSD1 Dwarf Spider Droid",
    filename: "",
    keywords: [
      "self_destruct_x",
      "armor_x",
      "climb_vehicle",
      "expert_climber",
      "programmed",
      "blast",
      "impact_x",
    ],
    hiddenFromPrint: true,
  },
  {
    name: "Droidekas",
    filename: "",
    keywords: [
      "ai_action",
      "generator_x",
      "shielded_x",
      "wheel_mode",
      "cover_x",
      "suppressive",
      "fixed",
      "immune_deflect",
    ],
    hiddenFromPrint: true,
  },
  {
    name: "LM-432 Crab Droid",
    filename: "",
    keywords: [
      "armor_x",
      "climb_vehicle",
      "programmed",
      "reposition",
      "scale",
      "scout_x",
      "scouting_party_x",
      "impact_x",
      "pierce_x",
    ],
    hiddenFromPrint: true,
    keywordsOnly: true,
  },
  {
    name: "STAP Riders",
    filename: "",
    keywords: [
      "agile_x",
      "ai_action",
      "coordinate",
      "cover_x",
      "speeder_x",
      "critical_x",
      "fixed",
    ],
    hiddenFromPrint: true,
  },
  {
    name: "Aqua Droids",
    filename: "",
    keywords: ["ai_action", "armor_x", "infiltrate", "impact_x"],
    hiddenFromPrint: true,
    keywordsOnly: true,
  },
];

export const CISCards: BaseCard[] = cards_cis_base.map((card) => {
  return { ...card, faction: CIS };
});
