import { BaseCard, EMPIRE } from "../types";

export const EmpireCards: BaseCard[] = (
  [
    {
      filename: "at_st",
      name: "AT-ST",
      hiddenFromPrint: false,
      keywords: ["armor_x", "arsenal_x", "weak_point_x", "fixed", "impact_x"],
    },
    {
      filename: "dark_troopers",
      name: "Imperial Dark Troopers",
      hiddenFromPrint: false,
      keywords: ["armor_x", "plodding", "unconcerned", "unstoppable"],
    },
    {
      filename: "e-web",
      name: "E-Web Heavy Blaster Team",
      hiddenFromPrint: false,
      keywords: [
        "prepared_positions",
        "reposition",
        "sentinel",
        "cumbersome",
        "fixed",
        "impact_x",
      ],
    },
    {
      filename: "imperial_officer",
      name: "Imperial Officer (Ruthless Commander)",
      hiddenFromPrint: false,
      keywords: ["spotter_x", "exemplar", "inspire_x"],
    },
    {
      filename: "laat_empire",
      name: "LAAT/le Patrol Transport",
      hiddenFromPrint: false,
      keywords: [
        "armor_x",
        "arsenal_x",
        "cover_x",
        "hover_x",
        "immune_blast",
        "immune_melee",
        "immune_range_1_weapons",
        "transport",
        "impact_x",
        "fixed",
      ],
    },
    {
      filename: "marquand",
      name: "Major Marquand (Tempest Scout 2)",
      hiddenFromPrint: false,
      keywords: [
        "armor_x",
        "arsenal_x",
        "direct",
        "field_commander",
        "weak_point_x",
        "special_issue",
        "fixed",
        "blast",
        "impact_x",
      ],
    },
    {
      filename: "orson_krennic",
      name: "Director Orson Krennic (Architect of Terror)",
      keywords: ["spotter_x", "compel", "cunning", "entourage", "exemplar"],
      hiddenFromPrint: false,
    },
    {
      filename: "scout_strike",
      name: "Scout Troopers (Strike Team)",
      hiddenFromPrint: false,
      keywords: ["detachment", "heavy_weapon_team", "low_profile", "scout_x"],
    },
    {
      filename: "shoretroopers",
      name: "Shoretroopers",
      hiddenFromPrint: false,
      keywords: [
        "coordinate",
        "emplacement_trooper",
        "prepared_positions",
        "long_shot",
      ],
    },
    {
      filename: "snowtroopers",
      name: "Snowtroopers",
      hiddenFromPrint: false,
      keywords: ["steady"],
    },
    {
      filename: "stormtroopers",
      name: "Stormtroopers",
      hiddenFromPrint: false,
      keywords: ["precise_x"],
    },
    {
      filename: "stormtroopers_hwu",
      name: "Stormtroopers (Heavy Response Unit)",
      hiddenFromPrint: false,
      keywords: [
        "flexible_response_x",
        "precise_x",
        "special_issue",
        "unhindered",
      ],
    },
    {
      filename: "tx-225",
      name: "TX-225 GAVw Occupier Tank",
      hiddenFromPrint: false,
      keywords: [
        "armor_x",
        "arsenal_x",
        "reposition",
        "transport",
        "weak_point_x",
        "suppressive",
        "fixed",
        "impact_x",
      ],
    },
    {
      filename: "veers",
      name: "General Veers (Master Tactician)",
      hiddenFromPrint: false,
      keywords: [
        "guidance",
        "spotter_x",
        "exemplar",
        "inspire_x",
        "sharpshooter_x",
      ],
    },

    // NOT PRINT
    {
      filename: "",
      name: "74-Z Speeder Bikes",
      hiddenFromPrint: true,
      keywords: ["cover_x", "speeder_x", "impact_x", "fixed"],
    },
    {
      filename: "",
      name: "Darth Vader (Dark Lord of The Sith)",
      hiddenFromPrint: true,
      keywords: [
        "compel",
        "deflect",
        "immune_pierce",
        "master_of_the_force",
        "relentless",
        "impact_x",
        "pierce_x",
      ],
    },
    {
      filename: "",
      name: "Fifth Brother",
      hiddenFromPrint: true,
      keywords: [
        "dauntless",
        "block",
        "enrage_x",
        "immune_pierce",
        "ram_x",
        "impact_x",
        "pierce_x",
      ],
    },
    {
      filename: "",
      name: "Seventh Sister",
      hiddenFromPrint: true,
      keywords: [
        "jump_x",
        "associate",
        "block",
        "charge",
        "disciplined_x",
        "immune_pierce",
        "impact_x",
        "pierce_x",
      ],
    },
    {
      filename: "",
      name: "Range Troopers",
      hiddenFromPrint: true,
      keywords: [
        "advanced_targeting_x",
        "armor_x",
        "indomitable",
        "scale",
        "spur",
      ],
    },
    {
      filename: "",
      name: "Agent Kallus (Hunter of Spectres)",
      hiddenFromPrint: true,
      keywords: [
        "contingencies_x",
        "cunning",
        "flawed",
        "sharpshooter_x",
        "tactical_x",
        "pierce_x",
      ],
    },
    {
      filename: "",
      name: "DF-90 Mortar Trooper",
      hiddenFromPrint: true,
      keywords: [
        "detachment",
        "fire_support",
        "full_pivot",
        "reposition",
        "sentinel",
        "critical_x",
        "cumbersome",
        "suppressive",
        "fixed",
      ],
    },
    {
      filename: "",
      name: "Imperial Special Forces (Inferno Squad)",
      hiddenFromPrint: true,
      keywords: ["equip", "infiltrate", "marksman", "reliable_x", "retinue"],
    },
    {
      filename: "",
      name: "Imperial Special Forces",
      hiddenFromPrint: true,
      keywords: ["infiltrate", "marksman", "reliable_x"],
    },
    {
      filename: "",
      name: "Iden Versio (Inferno Squad Leader)",
      hiddenFromPrint: true,
      keywords: [
        "quick_thinking",
        "covert_ops",
        "loadout",
        "marksman",
        "infiltrate",
        "pierce_x",
      ],
    },
    {
      filename: "",
      name: "Iden's ID10 Seeker Droid",
      hiddenFromPrint: true,
      keywords: [
        "counterpart",
        "recharge_x",
        "shielded_x",
        "small",
        "suppressive",
      ],
    },
    {
      filename: "",
      name: "Dewback Rider",
      hiddenFromPrint: true,
      keywords: [
        "armor_x",
        "relentless",
        "reposition",
        "spur",
        "unhindered",
        "critical_x",
        "suppressive",
      ],
    },
    {
      filename: "",
      name: "Darth Vader (The Emperor's Apprentice)",
      hiddenFromPrint: true,
      keywords: [
        "deflect",
        "immune_pierce",
        "jedi_hunter",
        "master_of_the_force",
        "relentless",
        "impact_x",
        "pierce_x",
        "blast",
        "scatter",
      ],
    },
    {
      filename: "",
      name: "Imperial Royal Guards",
      hiddenFromPrint: true,
      keywords: ["charge", "disciplined_x", "guardian_x"],
    },
    {
      filename: "",
      name: "Imperial Death Troopers",
      hiddenFromPrint: true,
      keywords: ["disciplined_x", "precise_x", "ready_x"],
    },
    {
      filename: "",
      name: "Scout Troopers",
      hiddenFromPrint: true,
      keywords: ["low_profile", "scout_x", "sharpshooter_x"],
    },
    {
      filename: "",
      name: "Moff Gideon (Long Live the Empire)",
      hiddenFromPrint: true,
      keywords: [
        "observe_x",
        "entourage",
        "ruthless",
        "sharpshooter_x",
        "tactical_x",
        "pierce_x",
      ],
    },
    {
      filename: "",
      name: "Emperor Palpatine (Ruler of the Galactic Empire)",
      hiddenFromPrint: true,
      keywords: [
        "pulling_the_strings",
        "entourage",
        "immune_pierce",
        "master_of_the_force",
        "pierce_x",
        "suppressive",
      ],
    },
    {
      filename: "",
      name: "Riot Control Squad",
      hiddenFromPrint: true,
      keywords: ["charge", "hold_the_line", "suppressive"],
    },
  ] as BaseCard[]
).map((card) => {
  return { ...card, faction: EMPIRE };
});
