import { BaseCard, GAR } from "../types";

export const GarCards: BaseCard[] = [
  {
    faction: GAR,
    name: "Anakin Skywalker (The Chosen One)",
    filename: "anakin",
    keywords: [
      "djem_so_mastery",
      "tempted",
      "jump_x",
      "charge",
      "deflect",
      "immune_pierce",
      "master_of_the_force",
      "impact_x",
      "pierce_x",
    ],
    hiddenFromPrint: false,
  },
  {
    faction: GAR,
    name: "Padmé Amidala (Spirited Senator)",
    filename: "padme",
    keywords: ["bolster_x", "agile_x", "inspire_x", "nimble", "sharpshooter_x"],
    hiddenFromPrint: false,
  },
  {
    faction: GAR,
    name: "ARC Troopers",
    filename: "arc_troopers",
    keywords: [
      "charge",
      "impervious",
      "scale",
      "scout_x",
      "sharpshooter_x",
      "tactical_x",
    ],
    hiddenFromPrint: false,
  },
  {
    faction: GAR,
    name: "ARF Troopers",
    filename: "",
    keywords: ["observe_x", "scout_x", "low_profile", "unhindered"],
    hiddenFromPrint: true,
    keywordsOnly: true,
  },
  {
    faction: GAR,
    name: "ARC Troopers (Strike Team)",
    filename: "arc_troopers_strike",
    keywords: [
      "charge",
      "detachment",
      "heavy_weapon_team",
      "impervious",
      "scale",
      "scout_x",
      "sharpshooter_x",
      "tactical_x",
    ],
    hiddenFromPrint: false,
  },
  {
    faction: GAR,
    name: "AT-RT",
    filename: "at_rt_gar",
    keywords: [
      "armor_x",
      "climb_vehicle",
      "expert_climber",
      "scout_x",
      "impact_x",
      "critical_x",
    ],
    hiddenFromPrint: false,
  },
  {
    faction: GAR,
    name: "Clone Trooper Infantry",
    filename: "clone_trooper",
    keywords: ["reliable_x"],
    hiddenFromPrint: false,
  },
  {
    faction: GAR,
    name: "LAAT/le Patron Transport",
    filename: "laat_gar",
    keywords: [
      "armor_x",
      "arsenal_x",
      "cover_x",
      "hover_x",
      "immune_blast",
      "immune_melee",
      "immune_range_1_weapons",
      "transport",
      "fixed",
      "impact_x",
    ],
    hiddenFromPrint: false,
  },
  {
    faction: GAR,
    name: "Obi-Wan Kenobi (Civilized Warrior)",
    filename: "obiwan",
    keywords: [
      "soresu_mastery",
      "master_of_the_force",
      "deflect",
      "jump_x",
      "charge",
      "guardian_x",
      "immune_pierce",
    ],
    hiddenFromPrint: false,
  },
  {
    faction: GAR,
    name: "R2-D2 (Hero of a Thousand Devices)",
    filename: "r2d2_gar",
    keywords: ["repair_x", "inconspicious", "infiltrate", "secret_mission"],
    hiddenFromPrint: false,
  },
  {
    faction: GAR,
    name: "Raddaugh Gnasp Fluttercraft (Attack Craft)",
    filename: "raddaugh",
    keywords: [
      "attack_run",
      "cover_x",
      "immune_blast",
      "immune_melee",
      "immune_range_1_weapons",
      "reposition",
      "speeder_x",
      "special_issue",
    ],
    hiddenFromPrint: false,
  },
  {
    faction: GAR,
    name: "Saber-Class Tank",
    filename: "saber_class",
    keywords: [
      "armor_x",
      "arsenal_x",
      "hover_x",
      "outmaneuver",
      "weak_point_x",
      "critical_x",
      "fixed",
      "impact_x",
    ],
    hiddenFromPrint: false,
  },
  {
    faction: GAR,
    name: "Yoda (Grand Master of the Jedi Order)",
    filename: "yoda",
    keywords: [
      "ataru_mastery",
      "guidance",
      "deflect",
      "immune_pierce",
      "master_of_the_force",
      "impact_x",
      "pierce_x",
      "blast",
      "suppressive",
    ],
    hiddenFromPrint: false,
  },

  // NON PRINT
  {
    faction: GAR,
    name: "Chewbacca (Hero of Kashyyk)",
    filename: "",
    keywords: [
      "enrage_x",
      "guardian_x",
      "charge",
      "reliable_x",
      "scale",
      "lethal_x",
      "critical_x",
      "pierce_x",
      "impact_x",
    ],
    hiddenFromPrint: true,
  },
  {
    faction: GAR,
    name: "Clone Captain Rex (Honorable Soldier)",
    filename: "",
    keywords: [
      "gunslinger",
      "scout_x",
      "scouting_party_x",
      "sharpshooter_x",
      "tactical_x",
    ],
    hiddenFromPrint: true,
  },
  {
    faction: GAR,
    name: "Clone Commander (Trained for Leadership)",
    filename: "",
    keywords: ["bolster_x", "direct", "sharpshooter_x"],
    hiddenFromPrint: true,
  },

  {
    faction: GAR,
    name: "Wookiee Warriors (Kashyyk Defenders)",
    filename: "",
    keywords: ["indomitable", "scale", "sharpshooter_x"],
    hiddenFromPrint: true,
  },
  {
    faction: GAR,
    name: "Wookiee Warriors (Noble Fighters)",
    filename: "",
    keywords: [
      "charge",
      "duelist",
      "pierce_x",
      "immune_pierce",
      "indomitable",
      "scale",
    ],
    hiddenFromPrint: true,
  },
  {
    faction: GAR,
    name: "Wookiee Chieftain (Clan Leader)",
    filename: "",
    keywords: [
      "agile_x",
      "charge",
      "duelist",
      "pierce_x",
      "immune_pierce",
      "indomitable",
      "scale",
      "impact_x",
    ],
    hiddenFromPrint: true,
  },
  {
    faction: GAR,
    name: "Clone Commander Cody (Leader of the 212th)",
    filename: "",
    keywords: [
      "observe_x",
      "jump_x",
      "take_cover_x",
      "direct",
      "target_x",
      "lethal_x",
      "impact_x",
    ],
    hiddenFromPrint: true,
  },
  {
    faction: GAR,
    name: "Clone Commandos (Delta Squad)",
    filename: "",
    keywords: [
      "complete_the_mission",
      "critical_x",
      "equip",
      "infiltrate",
      "independent_x",
      "recover",
      "recharge_x",
      "target_x",
      "shielded_x",
      "suppressive",
    ],
    hiddenFromPrint: true,
  },
  {
    faction: GAR,
    name: "Clone Commandos",
    filename: "",
    keywords: [
      "complete_the_mission",
      "critical_x",
      "equip",
      "infiltrate",
      "recharge_x",
      "target_x",
      "shielded_x",
      "suppressive",
    ],
    hiddenFromPrint: true,
  },
  {
    faction: GAR,
    name: "The Bad Batch (Clone Force 99)",
    filename: "",
    keywords: [
      "equip",
      "impervious",
      "scale",
      "steady",
      "sharpshooter_x",
      "we_are_not_regs",
      "fire_support",
    ],
    hiddenFromPrint: true,
  },
  {
    faction: GAR,
    name: "C-3PO",
    filename: "",
    keywords: ["calculate_odds", "distract", "counterpart"],
    hiddenFromPrint: true,
  },
  {
    faction: GAR,
    name: "BARC Speeder",
    filename: "",
    keywords: ["arsenal_x", "cover_x", "speeder_x", "fixed"],
    hiddenFromPrint: true,
  },
  {
    faction: GAR,
    name: "Raddaugh Gnasp Fluttercraft",
    filename: "",
    keywords: [
      "cover_x",
      "immune_blast",
      "immune_melee",
      "immune_range_1_weapons",
      "reposition",
      "speeder_x",
    ],
    hiddenFromPrint: true,
  },
  {
    faction: GAR,
    name: "Infantry Support Platform",
    filename: "",
    keywords: ["armor_x", "cover_x", "hover_x", "weak_point_x", "impact_x"],
    hiddenFromPrint: true,
  },
];
