import { BaseCard, MERCENARY } from "../types";

const cards_mercs_base: Omit<BaseCard, "faction">[] = [
  {
    filename: "aa5_speeder_truck",
    name: "A-A5 Speeder Truck",
    hiddenFromPrint: false,
    affiliation: "raiders",
    keywords: ["armor_x", "hover_x", "reposition", "transport", "weak_point_x"],
  },
  {
    filename: "chewbacca",
    name: "Chewbacca (Let the Wookie Win)",
    hiddenFromPrint: false,
    affiliation: "ewoks",
    keywords: [
      "armor_x",
      "arsenal_x",
      "inspire_x",
      "incognito",
      "weak_point_x",
      "fixed",
      "blast",
      "impact_x",
    ],
  },
  {
    filename: "ewok_skirmishers",
    name: "Ewok Skirmishers",
    hiddenFromPrint: false,
    affiliation: "ewoks",
    keywords: ["mercenary", "low_profile", "unhindered"],
  },
  {
    filename: "ewok_slingers",
    name: "Ewok Slingers",
    hiddenFromPrint: false,
    affiliation: "ewoks",
    keywords: [
      "mercenary",
      "independent_x",
      "low_profile",
      "target_x",
      "primitive",
    ],
  },

  // NOT PRINT
  {
    filename: "",
    name: "Din Djarin (The Mandalorian)",
    hiddenFromPrint: true,
    affiliation: "rogue",
    keywords: [
      "arsenal_x",
      "bounty",
      "impervious",
      "independent_x",
      "tactical_x",
      "lethal_x",
      "long_shot",
      "versatile",
    ],
  },
  {
    filename: "",
    name: "Grogu (The Child)",
    hiddenFromPrint: true,
    affiliation: "rogue",
    keywords: ["counterpart", "hunted", "latent_power", "small"],
  },
  {
    filename: "",
    name: "The Bad Batch (Clone Force 99)",
    hiddenFromPrint: true,
    affiliation: "rogue",
    keywords: [
      "equip",
      "impervious",
      "scale",
      "steady",
      "sharpshooter_x",
      "we_are_not_regs",
    ],
  },
  {
    filename: "",
    name: "Omega (Mascot of the 99th)",
    hiddenFromPrint: true,
    affiliation: "rogue",
    keywords: ["counterpart", "im_part_of_the_squad_too"],
  },
  {
    filename: "",
    name: "IG-88 (Notorious Assassin Droid)",
    hiddenFromPrint: true,
    affiliation: "rogue",
    keywords: [
      "armor_x",
      "arsenal_x",
      "bounty",
      "impervious",
      "sharpshooter_x",
      "pierce_x",
      "versatile",
    ],
  },
  {
    filename: "",
    name: "IG-88 (Nurse and Protect)",
    hiddenFromPrint: true,
    affiliation: "rogue",
    keywords: [
      "armor_x",
      "gunslinger",
      "impervious",
      "programmed",
      "sharpshooter_x",
      "pierce_x",
    ],
  },
  {
    filename: "",
    name: "Bossk (Trandoshan Terror)",
    hiddenFromPrint: true,
    affiliation: "rogue",
    keywords: [
      "bounty",
      "enrage_x",
      "independent_x",
      "regenerate",
      "scale",
      "pierce_x",
      "suppressive",
    ],
  },
  {
    filename: "",
    name: "Cad Bane (Needs No Introduction)",
    hiddenFromPrint: true,
    affiliation: "rogue",
    keywords: [
      "jump_x",
      "bounty",
      "danger_sense",
      "independent_x",
      "sharpshooter_x",
      "steady",
      "pierce_x",
    ],
  },
  {
    filename: "",
    name: "Boba Fett (Infamous Bounty Hunter)",
    hiddenFromPrint: true,
    affiliation: "rogue",
    keywords: [
      "jump_x",
      "arsenal_x",
      "bounty",
      "impervious",
      "independent_x",
      "sharpshooter_x",
      "impact_x",
      "versatile",
      "pierce_x",
    ],
  },
  {
    filename: "",
    name: "Boba Fett (Daimyo of Mos Espa)",
    hiddenFromPrint: true,
    affiliation: "rogue",
    keywords: [
      "jump_x",
      "arsenal_x",
      "impervious",
      "independent_x",
      "standby",
      "sentinel",
      "sharpshooter_x",
      "tactical_x",
      "pierce_x",
    ],
  },
  {
    filename: "",
    name: "Black Sun Vigo",
    hiddenFromPrint: true,
    affiliation: "black_sun",
    keywords: ["aid", "dauntless", "independent_x"],
  },
  {
    filename: "",
    name: "Gar Saxon (Militant Commando)",
    hiddenFromPrint: true,
    affiliation: "maul_loyalists",
    keywords: [
      "jump_x",
      "allies_of_convenience",
      "compel",
      "impervious",
      "pierce_x",
      "sharpshooter_x",
    ],
  },
  {
    filename: "",
    name: "Pyke Syndicate Capo",
    hiddenFromPrint: true,
    affiliation: "pyke_syndicate",
    keywords: ["aid", "danger_sense", "independent_x"],
  },
  {
    filename: "",
    name: "Maul (A Rival)",
    hiddenFromPrint: true,
    affiliation: "maul_loyalists",
    keywords: [
      "jump_x",
      "allies_of_convenience",
      "deflect",
      "immune_pierce",
      "juyo_mastery",
      "wound_x",
      "impact_x",
      "pierce_x",
    ],
  },
  {
    filename: "",
    name: "Black Sun Enforcers",
    hiddenFromPrint: true,
    affiliation: "black_sun",
    keywords: ["dauntless", "independent_x", "precise_x", "self_preservation"],
  },
  {
    filename: "",
    name: "Pyke Syndicate Foot Soldiers",
    hiddenFromPrint: true,
    affiliation: "pyke_syndicate",
    keywords: [
      "danger_sense",
      "outmaneuver",
      "self_preservation",
      "independent_x",
    ],
  },
  {
    filename: "",
    name: "Mandalorian Super Commandos",
    hiddenFromPrint: true,
    affiliation: "maul_loyalists",
    keywords: ["jump_x", "defend_x", "impervious", "pierce_x", "independent_x"],
  },
  {
    filename: "",
    name: "Swoop Bike Riders",
    hiddenFromPrint: true,
    affiliation: "raiders",
    keywords: [
      "cover_x",
      "independent_x",
      "reinforcements",
      "speeder_x",
      "overrun_x",
    ],
  },
];

export const MercCards = cards_mercs_base.map((card) => {
  return { ...card, faction: MERCENARY } as BaseCard;
});
