import { BaseCard, REBEL } from "../types";

const cards_rebel_base: Omit<BaseCard, "faction">[] = [
  {
    filename: "1.4_fd_laser_cannon_team",
    name: "1.4 FD Laser Cannon Team",
    hiddenFromPrint: false,
    keywords: [
      "full_pivot",
      "prepared_positions",
      "sentinel",
      "stationary",
      "impact_x",
      "fixed",
    ],
  },
  {
    filename: "a-a5_speeder_truck_rebel",
    name: "A-A5 Speeder Truck",
    hiddenFromPrint: false,
    keywords: ["armor_x", "hover_x", "reposition", "transport", "weak_point_x"],
  },
  {
    filename: "at_rt_rebel",
    name: "AT-RT",
    hiddenFromPrint: false,
    keywords: [
      "armor_x",
      "climb_vehicle",
      "expert_climber",
      "scout_x",
      "impact_x",
    ],
  },
  {
    filename: "fleet_troopers",
    name: "Fleet Troopers",
    hiddenFromPrint: false,
    keywords: ["charge"],
  },
  {
    filename: "leia_organa",
    name: "Leia Organa (Fearless and Inventive)",
    hiddenFromPrint: false,
    keywords: [
      "take_cover_x",
      "exemplar",
      "inspire_x",
      "nimble",
      "sharpshooter_x",
    ],
  },
  {
    filename: "luke_skywalker_hero",
    name: "Luke Skywalker (Hero of the Rebellion)",
    hiddenFromPrint: false,
    keywords: [
      "jump_x",
      "block",
      "charge",
      "immune_pierce",
      "inspire_x",
      "sharpshooter_x",
      "impact_x",
      "pierce_x",
      "long_shot",
    ],
  },
  {
    filename: "r2d2_hero",
    name: "R2-D2 (Hero of a Thousand Devices)",
    hiddenFromPrint: false,
    keywords: [
      "repair_x",
      "inconspicious",
      "infiltrate",
      "secret_mission",
      "suppressive",
    ],
  },
  {
    filename: "rebel_commandos",
    name: "Rebel Commandos (Strike Team)",
    hiddenFromPrint: false,
    keywords: [
      "detachment",
      "heavy_weapon_team",
      "low_profile",
      "scout_x",
      "sharpshooter_x",
    ],
  },
  {
    filename: "rebel_officer",
    name: "Rebel Officer (Resolute Commander)",
    hiddenFromPrint: false,
    keywords: ["take_cover_x", "exemplar", "inspire_x"],
  },
  {
    filename: "rebel_troopers",
    name: "Rebel Troopers",
    hiddenFromPrint: false,
    keywords: ["nimble", "agile_x"],
  },
  {
    filename: "rebel_veterans",
    name: "Rebel Veterans",
    hiddenFromPrint: false,
    keywords: [
      "coordinate",
      "emplacement_trooper",
      "low_profile",
      "prepared_positions",
    ],
  },
  {
    filename: "t-47",
    name: "T-47 Airspeeder",
    hiddenFromPrint: false,
    keywords: [
      "armor_x",
      "arsenal_x",
      "cover_x",
      "immune_blast",
      "immune_melee",
      "immune_range_1_weapons",
      "speeder_x",
      "impact_x",
      "fixed",
    ],
  },
  {
    filename: "x-34_landspeeder",
    name: "X-34 Landspeeder",
    hiddenFromPrint: false,
    keywords: ["armor_x", "arsenal_x", "cover_x", "speeder_x"],
  },

  // NOT PRINT:
  {
    filename: "",
    name: "K-2SO (Sardonic Security Droid)",
    hiddenFromPrint: true,
    keywords: [
      "calculate_odds",
      "armor_x",
      "detachment",
      "incognito",
      "teamwork",
    ],
  },
  {
    filename: "",
    name: "Cassian Andor (Capable Intelligence Agent)",
    hiddenFromPrint: true,
    keywords: [
      "covert_ops",
      "danger_sense",
      "loadout",
      "marksman",
      "tactical_x",
      "pierce_x",
    ],
  },
  {
    filename: "",
    name: "Mandalorian Resistance (Clan Wren)",
    hiddenFromPrint: true,
    keywords: ["jump_x", "equip", "impervious", "nimble", "retinue"],
  },
  {
    filename: "",
    name: "Rebel Sleeper Cell (Ready to Strike)",
    hiddenFromPrint: true,
    keywords: ["nimble", "scout_x", "tactical_x", "impact_x", "suppressive"],
  },
  {
    filename: "",
    name: "Wookiee Warriors (Kashyyk Resistance)",
    hiddenFromPrint: true,
    keywords: ["indomitable", "scale", "sharpshooter_x"],
  },
  {
    filename: "",
    name: "Mark II Medium Blaster Trooper",
    hiddenFromPrint: true,
    keywords: [
      "detachment",
      "fire_support",
      "full_pivot",
      "reposition",
      "sentinel",
    ],
  },
  {
    filename: "",
    name: "Lando Calrissian (Smooth Operator)",
    hiddenFromPrint: true,
    keywords: [
      "contingencies_x",
      "covert_ops",
      "flawed",
      "sharpshooter_x",
      "uncanny_luck_x",
      "pierce_x",
      "infiltrate",
    ],
  },
  {
    filename: "",
    name: "Mandalorian Resistance",
    hiddenFromPrint: true,
    keywords: ["jump_x", "impervious", "pierce_x", "nimble"],
  },
  {
    filename: "",
    name: "C-3PO (Human-Cyborg Relations)",
    hiddenFromPrint: true,
    keywords: ["calculate_odds", "distract", "inconspicious", "counterpart"],
  },
  {
    filename: "",
    name: "Chewbacca (Walking Carpet)",
    hiddenFromPrint: true,
    keywords: [
      "enrage_x",
      "guardian_x",
      "scale",
      "charge",
      "teamwork",
      "lethal_x",
      "impact_x",
      "pierce_x",
    ],
  },
  {
    filename: "",
    name: "Han Solo (Unorthodox General)",
    hiddenFromPrint: true,
    keywords: [
      "low_profile",
      "gunslinger",
      "sharpshooter_x",
      "uncanny_luck_x",
      "pierce_x",
    ],
  },
  {
    filename: "",
    name: "Sabine Wren (Explosive Artist)",
    hiddenFromPrint: true,
    keywords: [
      "jump_x",
      "gunslinger",
      "impervious",
      "pierce_x",
      "nimble",
      "pierce_x",
    ],
  },
  {
    filename: "",
    name: "Ahsoka Tano (Fulcrum)",
    hiddenFromPrint: true,
    keywords: [
      "jump_x",
      "charge",
      "defend_x",
      "deflect",
      "immune_pierce",
      "jarkai_mastery",
      "impact_x",
      "pierce_x",
    ],
  },
  {
    filename: "",
    name: "Wicket (Hero of Bright Tree)",
    hiddenFromPrint: true,
    keywords: [
      "independent_x",
      "low_profile",
      "relentless",
      "scout_x",
      "scouting_party_x",
      "sharpshooter_x",
      "unhindered",
      "pierce_x",
      "primitive",
    ],
  },
  {
    filename: "",
    name: "Logray (Superstitious Shaman)",
    hiddenFromPrint: true,
    keywords: [
      "aid",
      "independent_x",
      "inspire_x",
      "low_profile",
      "nimble",
      "suppressive",
    ],
  },
  {
    filename: "",
    name: "C-3PO (Golden God)",
    hiddenFromPrint: true,
    keywords: [
      "master_storyteller",
      "compel",
      "divine_influence",
      "infiltrate",
      "guardian_x",
    ],
  },
  {
    filename: "",
    name: "Wookiee Warriors",
    hiddenFromPrint: true,
    keywords: ["charge", "expert_climber", "indomitable", "unhindered"],
  },
  {
    filename: "",
    name: "Wookiee Warriors (Freedom Fighters)",
    hiddenFromPrint: true,
    keywords: [
      "charge",
      "duelist",
      "pierce_x",
      "immune_pierce",
      "indomitable",
      "scale",
    ],
  },
  {
    filename: "",
    name: "Rebel Commandos",
    hiddenFromPrint: true,
    keywords: ["low_profile", "scout_x", "sharpshooter_x"],
  },
  {
    filename: "",
    name: "Jyn Erso (Stardust)",
    hiddenFromPrint: true,
    keywords: [
      "quick_thinking",
      "danger_sense",
      "infiltrate",
      "nimble",
      "sharpshooter_x",
      "suppressive",
    ],
  },
  {
    filename: "",
    name: "Rebel Pathfinders",
    hiddenFromPrint: true,
    keywords: ["danger_sense", "dauntless", "infiltrate"],
  },
  {
    filename: "",
    name: "Tauntaun Riders",
    hiddenFromPrint: true,
    keywords: [
      "agile_x",
      "relentless",
      "reposition",
      "sharpshooter_x",
      "unhindered",
      "ram_x",
    ],
  },
];

export const RebelCards = cards_rebel_base.map((card) => {
  return { ...card, faction: REBEL } as BaseCard;
});
